version: "3.8"

services:

  apache:
    container_name: apache
    restart: unless-stopped
    build:
      context: "./apache/"
    depends_on:
      - php
      - postgresql
    networks:
      - frontend
      - backend
    ports:
      - "8000:80"
    volumes:
      - "./public_html:/var/www/html:rw"
      - "./moodledata:/app/moodledata:rw"
  
  php:
    container_name: php
    restart: unless-stopped
    build:
      context: "./php/"
    networks:
      - backend
    volumes:
      - "./public_html:/var/www/html:rw"
      - "./moodledata:/app/moodledata:rw"
      - "./bht_moodledata:/app/bht_moodledata:rw"

  cron:
    container_name: cron
    restart: unless-stopped
    build:
      context: "./cron/"
    networks:
      - backend
    volumes:
      - "./public_html:/var/www/html:rw"
      - "./moodledata:/app/moodledata:rw"
      - "./bht_moodledata:/app/bht_moodledata:rw"

  postgresql:
    container_name: postgresql
    build:
      context: "./postgresql/"
    networks:
      - backend
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - "./postgresql_data:/var/lib/postgresql/data:rw"

  adminer:
    container_name: adminer
    restart: unless-stopped
    build:
      context: "./adminer/"
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
